services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"  # Standard MQTT port     
    volumes:
      - /home/briansh/mqtt/mosquitto/config:/mosquitto/config  # Mount config directory
      - /home/briansh/mqtt/mosquitto/data:/mosquito/data      # Persistent storage for messages
      - /home/briansh/mqtt/mosquitto/log:/mosquitto/log        # Persistent storage for logs
    user: "1883:1883" # Use Mosquitto's default UID/GID for correct permissions on mounted volumes
                      